# Shell variables
# Generated by 'wal'
wallpaper="/home/u1dm/wallpapers/journeytosea-YMMnnRZFgEI-unsplash.jpg"

# Special
background='#191216'
foreground='#dedede'
cursor='#dedede'

# Colors
color0='#191216'
color1='#958871'
color2='#9A7887'
color3='#7A8183'
color4='#A19594'
color5='#B5B1AF'
color6='#C2BFBC'
color7='#dedede'
color8='#9b9b9b'
color9='#958871'
color10='#9A7887'
color11='#7A8183'
color12='#A19594'
color13='#B5B1AF'
color14='#C2BFBC'
color15='#dedede'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
